### PR TITLE
feat: tlog api integration

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff adjusts the api routes to use the new www api, which is now composed by plugins.

https://github.com/lukebp/politeia/tree/tlog/politeiawww/api

### CODE REVIEW

**Comment by lukebp** [comment]
- error handling needs to be fixed
- editing an unvetted proposal doesn't reflect the edit until you reload the page
- clicking back to a different proposal version is broken.  The pi `/proposals` route is only for fetching the data required to display the list views.  It doesn't return all of the files.  You should be using the record `/details` route.
- navigating to a single comment thread then clicking the "view all" button is broken
- i'm not seeing the "censor" button anywhere when looking at the unvetted proposal list view or the proposal details
- minor performance improvement, the unvetted list views don't need to check the vote summaries.  They're not going to exist for unvetted proposals.
- the backend doesn't allow a user to upvote/downvote their own comment.  The gui shouldn't allow them to either. 
- abandoned proposals are not showing up in the list views.  Keep in mind that the record inventory route groups them by record status and the record status for abandoned proposals is going to show up as "archived".  Abandoned is terminology that is specific to the proposal system so it won't be present in the generic `/records` routes.
- all github links need to be taken out.  These don't exist anymore.
- failed login attempts alignment is bad
image

## Proposal URLs

The politeiawww API has been made into a generic `/records` API that can be reused for any kind of record (proposals, invoices, DCCs, pi-reddit posts) and I think it would make sense for the gui to start heading in that direction as well.  The end goal is to be able to spin up a politeia instance for your individual use case, whether thats a DAO governance platform, a community forum, or a personal blog, without having to write any new code.  You just specify the functionality you want in the config (ex. versioned, timestamped records with the ability for users to create an account and add comments) and the backend and frontend just work.  Starting to make the URLs more generic to support this platform direction would hurt the UX a little bit, but its worth it imo because it allows us to turn politeia from an application specific frontend/backend into a platform that can be built upon for all kinds of applications.

An example of what the URLs might look like: 
unvetted: `/record/unvetted/1c13df9`
vetted: `/record/1c13df9`

Anyone have any thoughts on this? cc: @victorgcramos @tiagoalvesdulce @thi4go

**Comment by tiagoalvesdulce** [comment]
I suggest we add a variable in the config for the record name and use it in the URLs. The backend will not know about it, only the FE. Here is how we create a route in Politeia right now:

```
<AdminAuthenticatedRoute
 path={"/proposals/unvetted"}
 title={"Unvetted Proposals"}
 exact
 component={PageProposalsUnvetted}
/>
```

It's similar with CMS. We are doing the config verification one layer above and have separate components for Politeia's routes and CMS's routes

We would change it to something like:

```
...
const { recordName } = useConfig();
...
return (
<AdminAuthenticatedRoute
 path={`/${recordName}s/unvetted`}
 title={`Unvetted ${recordName}s`}
 exact
 component={PageRecordsUnvetted}
/>
)
```

Also, the routes to be created should be defined via config.

**Comment by victorgcramos** [comment]
@tiagoalvesdulce what if the same platform has 2 or more record types, such as Invoices and DCCs for CMS?

What I suggest here is to create a wrapper that parses record metadata and returns the correct view. In this case, we would only have a `/records/token` route.

**Comment by tiagoalvesdulce** [comment]
hmm, I guess it's fine to keep the `records/:token` route. I'm trying to think about something more user friendly but we risk overcomplicating things.

Edit: I went for a run and thought about this for a while. How would the user differentiate between the URLs with two different record types? Take invoices and DCCs as an example, both would be `records/:token`. We need that the user specifies all the record types so we can build the routes accordingly.

**Comment by victorgcramos** [comment]
we can have a list for each separate type of record. An Invoice list, a DCC list, Proposal list... However, the details page will necessarily fetch the record for the given token, this way we can parse the metadata and display the correct view. In this case, on Details page, we can use the `record/:token` approach.

The only concern is the token inventory. We need to find a way to filter between dccs and invoices to display them on a separate list. We used to have a `/tokeninventory` endpoint for each record type.

**Comment by lukebp** [comment]
Found another bug.

- the number of comments is not being shown on the list views.

**Comment by lukebp** [comment]
I'm also not sure that we can have the proposal list view tabs numbered anymore because of the way the inventory commands are setup.  The inventory calls are now paginated so that they can scale.  The tab numbering isn't really scalable anyway.  Once we get to hundreds or thousands of proposals do we really want a tab that says "Rejected 756".

**Comment by lukebp** [comment]
The rejected proposal tab is not being populated correctly.  The ticketvote inventory response is showing rejected votes but the rejected list is not showing any.

**Comment by lukebp** [comment]
Now that approve and rejected are their own vote status, there's no longer an `Approved` field, which is causing the `missing` tag.

image

**Comment by lukebp** [comment]
Censored vetted records are not showing up as censored.

image

**Comment by lukebp** [comment]
Current gui issues

- [x] replace `Ineligible` tab with `Abandoned` and don't show vetted censored proposals
- [ ] rejected vote list items are messed up
- [ ] proposal vote timestamps need a download button and workflow
- [ ] proposal bundle contents needs to match a records API `Record`
- [ ] consistent naming convention among download files
- [ ] proposal URLs are still `/proposals`
- [ ] paginate the vote summaries request.  Ex. if I have 10 proposals being
  voted on the gui requests the vote summaries for all 10 at the same time.
  This leads to longer load times. The vote summaries request should be split
  up to whatever size the gui page size is.
- [ ] minor perf improvement, the unvetted list views don't need to check
     the vote summaries. They're not going to exist for unvetted proposals.
- [x] error handling needs to be fixed
- [x] editing an unvetted proposal doesn't reflect the edit until you reload the
    page
- [x] clicking back to a different proposal version is broken. The pi /proposals
     route is only for fetching the data required to display the list views. It
     doesn't return all of the files. You should be using the record /details
     route.
- [x] navigating to a single comment thread then clicking the "view all" button
     is broken
- [x] abandoned proposals are not showing up in the list views. Keep in mind
     that the record inventory route groups them by record status and the
     record status for abandoned proposals is going to show up as "archived".
     Abandoned is terminology that is specific to the proposal system so it
     won't be present in the generic /records routes.
- [x] all github links need to be taken out. These don't exist anymore.
- [x] failed login attempts alignment is bad
- [x] number of comments are not being shown in the list views
- [x] remove proposal list view tab numbering
- [x] approved tag is showing as missing
- [x] i'm not seeing the "censor" button anywhere when looking at the unvetted
     proposal list view or the proposal details
- [x] the backend doesn't allow a user to upvote/downvote their own comment. The
     gui shouldn't allow them to either.
- [x] submit a proposal, go to the user details page to try and find the
     proposal in the user's proposal list. I get the error: `Error:
     PublicActions requires an PublicActionsProvider on a higher level of the
     component tree.` I was an admin, but I don't know if that matters.
     I get the same error when trying to view all unvetted proposals as an
     admin.
- [x] figure out list views

**Pull request closed without merging**
